SELECT TOP (1000) [Player]
      ,[Nation]
      ,[Pos]
      ,[Squad]
      ,[Comp]
      ,[Age]
      ,[Born]
      ,[MP]
      ,[Starts]
      ,[Min]
      ,[90s]
      ,[Gls]
      ,[Ast]
      ,[G+A]
      ,[G-PK]
      ,[PK]
      ,[PKatt]
      ,[CrdY]
      ,[CrdR]
      ,[xG]
      ,[npxG]
      ,[xAG]
      ,[npxG+xAG]
      ,[PrgC]
      ,[PrgP]
      ,[PrgR]
      ,[Gls_90]
      ,[Ast_90]
      ,[G+A_90]
      ,[G-PK_90]
      ,[G+A-PK_90]
      ,[xG_90]
      ,[xAG_90]
      ,[xG+xAG_90]
      ,[npxG_90]
      ,[npxG+xAG_90]
  FROM [ligas_fut].[dbo].[TOP_PLAYERS]

  SELECT Player, Gls FROM TOP_PLAYERS ORDER BY Gls DESC;
  SELECT Player, [G+A], Gls_90, Gls, Ast FROM TOP_PLAYERS ORDER BY [G+A] DESC;
  SELECT Comp, AVG(Gls) as promedio_goles FROM TOP_PLAYERS GROUP BY Comp;
  SELECT Squad, AVG(Gls) as promedio_por_equipo From TOP_PLAYERS GROUP BY Squad ORDER BY promedio_por_equipo DESC;